---
# tasks file for ansible-role-win-office365
- name: Make sure extract directory exist
  ansible.windows.win_file:
    path: '{{ office365_extract_dir }}'
    state: directory

- name: Download ODT
  ansible.windows.win_get_url:
    dest: "{{ office365_extract_dir }}"
    url: "{{ office365_odt_download_url }}"
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  register: download_odt_result

- name: Debug download_odt_result
  ansible.builtin.debug:
    var: download_odt_result

- name: Extract ODT
  ansible.windows.win_package:
    chdir: '{{ office365_extract_dir }}'
    path: '{{ download_odt_result.dest }}'
    state: present
    arguments: '/extract:{{ office365_extract_dir }} /quiet'

- name: Copy configuration.xml
  ansible.windows.win_copy:
    remote_src: no
    src: '{{ office365_configuration_xml }}'
    dest: '{{ office365_extract_dir }}\configuration.xml'

- name: Download Office365
  ansible.windows.win_package:
    chdir: '{{ office365_extract_dir }}'
    path: '{{ office365_extract_dir }}\setup.exe'
    state: present
    arguments: '/download configuration.xml'
  register: download_office365_result

- name: Debug download_office365_result
  ansible.builtin.debug:
    var: download_office365_result

- name: Configure Office365
  ansible.windows.win_package:
    chdir: '{{ office365_extract_dir }}'
    path: '{{ office365_extract_dir }}\setup.exe'
    state: present
    arguments: '/configure configuration.xml'
  register: configure_office365_result

- name: Debug configure_office365_result
  ansible.builtin.debug:
    var: configure_office365_result

- name: Remove extract directory
  ansible.windows.win_file:
    path: '{{ office365_extract_dir }}'
    state: absent

# Update Office365 Block
- name: Update Office365
  block:
    - name: Update Office 365 (no version specified)
      ansible.windows.win_command:
        cmd: "{{ office365_update_cmd }}"
      register: office365_update_result
      when: (office365_update_to_version is undefined) or (office365_update_to_version | length < 1)

    - name: Update Office 365 (specific version)
      ansible.windows.win_command:
        cmd: "{{ office365_update_cmd }}  updatetoversion={{ office365_update_to_version }}"
      register: office365_update_result
      when:
        - office365_update_to_version is defined
        - office365_update_to_version | length > 0

    - name: Debug update_office365_result
      ansible.builtin.debug:
        var: office365_update_result

    # Wait 5 seconds so that ClickToRun sets ExecutingScenario-Registry value
    - name: Sleep for 5 seconds
      ansible.windows.win_shell: |
        Start-Sleep -Seconds 5

    # Wait until ExecutingScenario-Registry value is removed.
    # This indicates that the update process is finished
    - name: Wait until ExecutingScenario is removed from registry
      ansible.windows.win_reg_stat:
        path: HKLM:\SOFTWARE\Microsoft\Office\ClickToRun
        name: ExecutingScenario
      register: reg_value_result
      until: reg_value_result.exists == false
      retries: 60
      delay: 10

    # Kill dialog which is display at the end of the update process
    - name: Kill OfficeC2RClient.exe process
      ansible.windows.win_shell: taskkill /F /IM OfficeC2RClient.exe
      ignore_errors: true

  tags: [never, office365-update]
...
