---
# tasks file for ansible-role-win-office365
- name: Make sure extract directory exist
  ansible.windows.win_file:
    path: '{{ office365_extract_dir }}'
    state: directory

- name: Copy configuration.xml
  ansible.windows.win_copy:
    remote_src: no
    src: '{{ office365_configuration_xml }}'
    dest: '{{ office365_extract_dir }}\configuration.xml'

- name: Download setup.exe
  ansible.windows.win_get_url:
    dest: "{{ office365_extract_dir }}"
    url: "{{ office365_setup_download_url }}"
    validate_certs: '{{ validate_certs | default(omit) }}'
    proxy_password: '{{ proxy_password | default(omit) }}'
    proxy_url : '{{ proxy_url  | default(omit) }}'
    proxy_use_default_credential: '{{ use_default_credential | default(omit) }}'
    proxy_username: '{{ proxy_username | default(omit) }}'
  register: download_setup_exe_result

- name: Configure Office365
  ansible.windows.win_package:
    chdir: '{{ office365_extract_dir }}'
    path: '{{ download_setup_exe_result.dest }}'
    state: present
    arguments: '/configure configuration.xml'

- name: Remove extract directory
  ansible.windows.win_file:
    path: '{{ office365_extract_dir }}'
    state: absent

- name: Update Office 365
  ansible.windows.win_command:
    cmd: "{{ office365_update_cmd }}"
  register: office365_update_result
  tags: [never, office365-update]

- name: Debug update_office365_result
  ansible.builtin.debug:
    var: office365_update_result
  tags: [never, office365-update]
...
